# Generated by Django 5.0.4 on 2024-04-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='DNI'),
        ),
    ]
