# Generated by Django 5.0.4 on 2024-04-18 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='image',
        ),
        migrations.DeleteModel(
            name='CatalogImage',
        ),
    ]
