# Generated by Django 5.0.4 on 2024-04-22 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioApp', '0002_alter_user_dni'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('surname', models.CharField(max_length=100, verbose_name='Cognom')),
                ('surname2', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segon cognom (opcional)')),
                ('dni', models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='DNI')),
                ('date_of_birth', models.DateField(verbose_name='Data de naixement')),
                ('center', models.CharField(max_length=100, verbose_name='Centre al que pertany')),
                ('cycle', models.CharField(max_length=100, verbose_name='Curs al que pertany')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/', verbose_name='Imatge de perfil')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioApp.role', verbose_name="Rol d'usuari")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuari')),
            ],
            options={
                'verbose_name': "Perfil d'usuari",
                'verbose_name_plural': "Perfils d'usuari",
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
